// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReminderJobService.proto

package com.example.reminderJob.api;

public final class ReminderJobGrpcClient {
  private ReminderJobGrpcClient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ReminderJobService.proto\032\023ReminderCaus" +
      "a.proto2O\n\022ReminderJobService\0229\n\016addRemi" +
      "nderJob\022\017.ReminderJobReq\032\024.ReminderJobRe" +
      "sponse\"\000B4\n\033com.example.reminderJob.apiB" +
      "\025ReminderJobGrpcClientb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.reminderJob.protos.GrpcParams.getDescriptor(),
        }, assigner);
    com.example.reminderJob.protos.GrpcParams.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
